config/routes.rb
HonsProj::Application.routes.draw do
  root 'home#main'
  get 'search' => 'home#search'
  get 'import' => 'import#main'
  get 'cleardb' => 'import#clear'
  get 'recommend' => 'recommend#main'

end

app/models/positive.rb
class Positive < ActiveRecord::Base
  belongs_to :item, :class_name => 'Theorem'
  belongs_to :theorem
end

app/models/theorem.rb
class Theorem < ActiveRecord::Base
  default_scope { order('place ASC') }

  has_many :positives, :foreign_key => 'item_id'
  has_many :theorems, :through => :positives
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def main
  end

  def search
    @theorem = Theorem.find_by_name(params[:name])
  end

end

app/controllers/import_controller.rb
class ImportController < ApplicationController

  def main
    begin
      require 'csv'
      place = 1 + (Theorem.maximum(:place) || 0)
      CSV.foreach(params[:filepath], :headers => true) do |row|
        new_theorem = {place: place}
        new_theorem[:name] = row.to_hash['match']
        new_theorem[:is_item] = row.to_hash['item?']=='1'
        new_theorem[:place] = place
        if new_theorem[:is_item]
          new_theorem[:theorem_ids] = []
          theorem_names = row.to_hash['attributes'].split(',').uniq
          theorem_names.each do |tn|
            th = Theorem.find_by_name(tn)
            new_theorem[:theorem_ids] << th.id if th
          end
        end
        old_theorem = Theorem.find_by_name(new_theorem[:name])
        if old_theorem
          old_theorem.update_attributes(new_theorem)
        else
          Theorem.create(new_theorem)
          place += 1
        end
      end
      redirect_to root_path, notice: 'Import was successful'
    rescue
      redirect_to root_path, notice: 'Import failed'
    end
  end

  def clear
    Positive.delete_all
    Theorem.delete_all
    redirect_to root_path
  end

end

app/controllers/recommend_controller.rb
class RecommendController < ApplicationController

  def main
    theorems = params[:tns].split(',').map{|tn| Theorem.find_by_name(tn.strip)}
    theorem_ids = theorems.reject(&:nil?).map(&:id)
    positives = Positive.where(theorem_id: theorem_ids)
    item_ids = positives.map(&:item_id).uniq
    item_sims = item_ids.inject({}){|accum, ii| accum.merge!(ii => 0)}
    positives.each{|positive| item_sims[positive.item_id] += 1}
    @item_sims = item_sims.sort_by{|_key, value| value}.reverse

    top_items = @item_sims[0..2].map{|ii,sim| Theorem.find(ii)}
    top_simls = @item_sims[0..2].map{|ii,sim| sim}
    pot_posts = top_items.map(&:theorem_ids)
    rel_posts = pot_posts.flatten.uniq.reject{|p| theorem_ids.include? p}
    estims = {}
    rel_posts.each do |ti|
      estim = 0
      (0..2).each do |n|
        if pot_posts[n].include? ti
          estim += top_simls[n]
        end
      end
      estims[ti] = estim.to_f / top_simls.sum
    end
    @estims = estims.sort_by{|_key, value| value}.reverse
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/main.haml
.container
  %h2 Import data
  - if notice
    %p#notice.alert.alert-success.container= notice
  = form_tag('/import', method: 'get', class: 'form-inline') do
    .form-group= text_field_tag 'filepath', nil, placeholder: 'path/to/File.csv', class: 'form-control'
    = submit_tag 'Import', class: 'btn btn-primary'
  %p Please input the path of the CSV file you want to import. Relative paths are evaluated from the app's root directory. E.g. if you have a file 'Multivariate.csv' in the 'db' folder of your app, you would use 'db/Multivariate.csv' in the field above.

.container
  %h2 View a theorem
  = form_tag('/search', method: 'get', class: 'form-inline') do
    .form-group= text_field_tag 'name', nil, placeholder: 'THEOREM_NAME', class: 'form-control'
    = submit_tag 'Search', class: 'btn btn-primary'
  %p Search for a theorem from the imported data, see what other theorems it uses in its proof (if available).

.container
  %h2 Get recommendations
  = form_tag('/recommend', method: 'get') do
    .form-group= text_field_tag 'tns', nil, placeholder: 'THEOREM_1,THEOREM_2,THEOREM_3', class: 'form-control'
    = submit_tag 'Recommend', class: 'btn btn-primary'
  %p You can input the list of theorems you already used in your proof in the field above. Separate them by commas.

.container
  %h2 Reset the database
  = link_to 'Clear DB', '/cleardb', class: 'btn btn-danger', confirm: 'Are you sure you want to purge the database?'

app/views/home/search.haml
.container
  %h2 Search for
  %h3 '#{params[:name]}'

.container
  - if @theorem
    - if @theorem.is_item
      %h4= link_to 'Recommend', recommend_path(tns: @theorem.theorems.map(&:name).join(','))
      %h4 #{@theorem.name} uses the following theorems in its proof:
      %table.table.table-striped.table-hover.table-condensed
        %tr
          %th Name
          %th Search
          %th Recommend
        - @theorem.theorems.each do |theorem|
          %tr
            %td= theorem.name
            %td= link_to 'Link', search_path(name: theorem.name)
            %td
              - if theorem.is_item
                = link_to 'Link', recommend_path(tns: theorem.theorems.map(&:name).join(','))
              - else
                N/A
    - else
      %h4 #{@theorem.name} does not have a proof, although it is known. It might be a definition.
  - else
    %h4 No results were found.

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title HonsProj
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    -# ^^ recommended by bootstrap for mobile zooming ^^

%body
  .container
    %ul.list-inline.space-btns
      %li= link_to "Home", "/", class: "btn btn-primary"
    = yield

app/views/recommend/main.haml
.container
  %h2 Recommender results for
  %h3 '#{params['tns']}'
.container
  %h4 Theorems you could use to advance the proof
  %table.table.table-striped.table-hover.table-condensed
    %tr
      %th Name
      %th Estimate
      %th Search
      %th Recommend
    - @estims.each do |theorem_id, estim|
      - theorem = Theorem.find(theorem_id)
      %tr{:class => if (estim>=0.5) then 'success' else '' end}
        %td= theorem.name
        %td= estim.round(2)
        %td= link_to 'Link', search_path(name: theorem.name)
        %td
          - if theorem.is_item
            = link_to 'Link', recommend_path(tns: theorem.theorems.map(&:name).join(','))
          - else
            N/A

  %h4 Closest neighbours of the input. The recommendations are based on top 3 from below.
  %table.table
    %tr
      %th Name
      %th Similarity
      %th Search
      %th Recommend
    - @item_sims.each do |item_id, simil|
      - theorem = Theorem.find(item_id)
      %tr
        %td= theorem.name
        %td= simil
        %td= link_to 'Link', search_path(name: theorem.name)
        %td
          - if theorem.is_item
            = link_to 'Link', recommend_path(tns: theorem.theorems.map(&:name).join(','))
          - else
            N/A